(function () {
  // Katman 3 sahneleri: sabit durum + beklenen karar. Takım 0 sağa (Kuyu x=100) hücum eder.
  const A = (o) => ({ okuma: 10, aktarim: 10, tutus: 10, kesme: 10, yogunluk: 10, hiz: 10, cesaret: 10, surme: 10, ...(o || {}) });
  const P = (team, name, x, y, role, a) => ({ id: name, team, name, x, y, vx: 0, vy: 0, role: role || 'Orta', a: A(a), R: role === 'Bekçi' ? 7 : 8, D: role === 'Bekçi' ? 1.2 : 1 });
  const bek = () => P(1, 'Bekçi', 97, 25, 'Bekçi');
  const S = [
    { id: 's1', title: 'Baskı altında, boş arkadaş', why: 'Taşıyıcının dibinde rakip var; ileride hattı açık bir arkadaş. Basit pas vermeli.', ch: .3,
      expect: ['pas', 'önüne'], ps: () => [P(0, 'Taşıyıcı', 45, 25), P(0, 'Arkadaş', 60, 14), P(1, 'Presçi', 43.4, 26), P(1, 'Uzak', 70, 40), bek()] },
    { id: 's2', title: 'Baskı yok, arkadaşlar markajlı', why: 'Yakında rakip yok, arkadaşların ayağı kapalı. Ayağa pas atmamalı; tutup şarj toplamalı, sürmeli ya da markajcının geç tepki vereceği boşluğa (arkadaşın önüne) oynamalı.', ch: .3,
      expect: ['tut', 'sür', 'önüne'], ps: () => [P(0, 'Taşıyıcı', 35, 25), P(0, 'Arkadaş 1', 58, 12), P(0, 'Arkadaş 2', 58, 38), P(1, 'Markaj 1', 59.5, 13), P(1, 'Markaj 2', 59.5, 37), P(1, 'Orta', 62, 25), bek()] },
    { id: 's3', title: 'Kuyu önünde, şarjlı', why: 'Kuyu\'ya 16 birim, şarj %90, önünde tek savunmacı yan tarafta. Göndermeli.', ch: .9,
      expect: ['gönder'], ps: () => [P(0, 'Taşıyıcı', 84, 25), P(0, 'Arkadaş', 70, 40), P(1, 'Savunmacı', 89, 31), bek()] },
    { id: 's4', title: 'Doğrudan hat kapalı', why: 'Arkadaş aynı hatta ileride, arada savunmacı. Kenardan sektirmeli ya da başka çözüm bulmalı; doğrudan pas atmamalı.', ch: .4,
      expect: ['kenardan', 'önüne', 'tut', 'sür'], forbid: ['pas'], ps: () => [P(0, 'Taşıyıcı', 45, 42), P(0, 'Arkadaş', 72, 42), P(1, 'Engel', 58.5, 42), P(1, 'Uzak', 60, 15), bek()] },
    { id: 's5', title: 'Doğrudan hat açık', why: 'Aynı durum, ama arada savunmacı yok. Kenardan sektirmeye gerek yok; doğrudan pas.', ch: .4,
      expect: ['pas', 'önüne'], forbid: ['kenardan'], ps: () => [P(0, 'Taşıyıcı', 45, 42), P(0, 'Arkadaş', 66, 42), P(1, 'Uzak', 60, 15), bek()] },
    { id: 's6', title: 'Uzakta, şarjsız', why: 'Kuyu\'ya 27 birim, şarj %20, önü kalabalık. Göndermemeli.', ch: .2,
      expect: ['tut', 'sür', 'pas', 'önüne', 'kenardan'], forbid: ['gönder'], ps: () => [P(0, 'Taşıyıcı', 73, 25), P(0, 'Arkadaş', 70, 8), P(1, 'Savunmacı 1', 84, 22), P(1, 'Savunmacı 2', 84, 29), bek()] },
    { id: 's7', title: 'Hat kapalı, sürme de kapalı', why: 'Önü bir savunmacıyla kapalı, arkadaşına giden hattın ortasında bir engel var; kenar ise engelden uzak. Tek temiz yol kenardan sektirmek. Okuma 10\'un altındaki oyuncu bu çözümü görmez; baskı altında başka bir şey dener (çoğu zaman kötü sonuçlanır).', ch: .4,
      expect: ['kenardan'], needOk: 10, ps: () => [P(0, 'Taşıyıcı', 45, 30), P(0, 'Arkadaş', 75, 30), P(1, 'Engel', 60, 30), P(1, 'Önde', 49.5, 31), P(1, 'İçeride', 48.5, 25), P(1, 'Uzak', 86, 14), bek()] },
    { id: 'k1', group: 'Kuyu önü', title: 'Geri pas', why: 'Taşıyıcı çizgiye yakın, dar açıda. Savunma Kuyu önüne yığılmış; bir arkadaş geride, ortada boş. Göndermemeli, geriye boştakine vermeli.', ch: .5,
      expect: ['pas', 'önüne'], forbid: ['gönder'], ps: () => [P(0, 'Taşıyıcı', 92, 9), P(0, 'Boştaki', 79, 25), P(0, 'Markajlı', 90, 36), P(1, 'Yığın 1', 93, 21), P(1, 'Yığın 2', 92, 27), P(1, 'Yığın 3', 89, 24), P(1, 'Markaj', 91, 34), bek()] },
    { id: 'k2', group: 'Kuyu önü', title: 'İkiye bir', why: 'Kuyu önünde tek savunmacıya karşı iki hücumcu. Savunmacı taşıyıcının hattında: arkadaşa vermeli. Ya da hat açıksa göndermeli.', ch: .5,
      expect: ['pas', 'önüne', 'gönder'], forbid: ['tut'], ps: () => [P(0, 'Taşıyıcı', 80, 20), P(0, 'Arkadaş', 82, 33), P(1, 'Tek savunmacı', 86, 22.5), bek()] },
    { id: 'k3', group: 'Kuyu önü', title: 'Bekçiyle bire bir', why: 'Arada savunmacı yok, Kuyu\'ya 14 birim, şarj orta. Göndermeli; Bekçi\'nin uzanamayacağı köşeye plase ya da güçlü.', ch: .55,
      expect: ['gönder'], ps: () => [P(0, 'Taşıyıcı', 86, 25), P(0, 'Arkadaş', 70, 40), P(1, 'Geride', 72, 20), bek()] },
    { id: 'k4', group: 'Kuyu önü', title: 'Karşı taraf', why: 'Blok taşıyıcının tarafına kaymış; karşı tarafta bir arkadaş açık açıda. Ona vermeli, kalabalığa göndermemeli.', ch: .5,
      expect: ['pas', 'önüne', 'kenardan'], forbid: ['gönder'], ps: () => [P(0, 'Taşıyıcı', 82, 12), P(0, 'Karşıdaki', 85, 37), P(1, 'Kayan 1', 87, 14), P(1, 'Kayan 2', 90, 19), P(1, 'Kayan 3', 85, 19), bek()] },
    { id: 'k5', group: 'Kuyu önü', title: 'Kalabalık, açık yok', why: 'Önü 5 savunmacıyla dolu, arkadaşlar markajlı. Kalabalığa göndermemeli; tutup, geri verip yeniden kurmalı.', ch: .4,
      expect: ['tut', 'sür', 'pas', 'önüne', 'kenardan'], forbid: ['gönder'], ps: () => [P(0, 'Taşıyıcı', 74, 25), P(0, 'Arkadaş 1', 86, 15), P(0, 'Arkadaş 2', 86, 35), P(0, 'Geride', 60, 30), P(1, 'Blok 1', 84, 22), P(1, 'Blok 2', 84, 28), P(1, 'Blok 3', 90, 25), P(1, 'Markaj 1', 87.5, 16), P(1, 'Markaj 2', 87.5, 34), bek()] },
    { id: 'o1', group: 'Orta saha', title: 'Kanat değiştir (7\'ye 7)', why: 'Taşıyıcı sol kanatta, rakip blok onun tarafına kaymış. Sağ kanatta bir arkadaş boşta. Beklenen: Çekirdeği karşı kanada taşımak (doğrudan ya da merkezden), blok kayarken boşluğu kullanmak.', ch: .4,
      expect: ['pas', 'önüne', 'kenardan'], ps: () => [P(0, 'Taşıyıcı', 45, 10), P(0, 'Yakın', 50, 20), P(0, 'Karşı kanat', 55, 42), P(0, 'Uç', 66, 26), P(0, 'Pivot', 38, 30), P(0, 'Bek', 28, 22), P(0, 'Bizim Bekçi', 3, 25, 'Bekçi'), P(1, 'Blok 1', 53, 9), P(1, 'Blok 2', 55, 17), P(1, 'Blok 3', 60, 24), P(1, 'Blok 4', 64, 14), P(1, 'Arka 1', 70, 30), P(1, 'Arka 2', 76, 20), bek()] },
    { id: 'o2', group: 'Orta saha', title: 'Presi üstüne çek (7\'ye 7)', why: 'Rakip önde basıyor (3 kişi, yüksek blok). Taşıyıcının arkasında boş bir arkadaş var. Beklenen: presçiler gelince arkalarında açılan boşluğu kullanmak; gerekirse önce geri vererek presi çekmek.', ch: .4, tac: [{}, { pres: 3, blok: 'Yüksek' }],
      expect: ['pas', 'önüne', 'tut'], ps: () => [P(0, 'Taşıyıcı', 40, 25), P(0, 'Geride', 28, 28), P(0, 'Sol kanat', 52, 7), P(0, 'Sağ kanat', 52, 43), P(0, 'İleri', 62, 26), P(0, 'Bek', 32, 15), P(0, 'Bizim Bekçi', 3, 25, 'Bekçi'), P(1, 'Presçi 1', 44, 22), P(1, 'Presçi 2', 44, 29), P(1, 'Orta 1', 52, 18), P(1, 'Orta 2', 54, 33), P(1, 'Arka 1', 64, 25), P(1, 'Arka 2', 74, 24), bek()] },
    { id: 'o3', group: 'Orta saha', title: 'Hat arkasına sız (7\'ye 7)', why: 'Rakip savunma hattı önde (x≈66), arkası boş. Bir arkadaş hattın üstünde. Beklenen: hattın arkasına, koşucunun savunmadan önce varacağı yere pas ya da aşırtma.', ch: .4,
      expect: ['önüne', 'pas'], ps: () => [P(0, 'Taşıyıcı', 50, 25), P(0, 'Koşucu', 64, 30), P(0, 'Sol kanat', 60, 10), P(0, 'Sağ kanat', 58, 42), P(0, 'Orta', 45, 33), P(0, 'Bek', 35, 20), P(0, 'Bizim Bekçi', 3, 25, 'Bekçi'), P(1, 'Hat 1', 66, 16), P(1, 'Hat 2', 66, 26), P(1, 'Hat 3', 66, 36), P(1, 'Orta 1', 56, 22), P(1, 'Orta 2', 57, 32), P(1, 'Kanatçı', 60, 44), bek()] },
    { id: 'd1', group: 'Savunma', title: 'Düşük blok · rakip dolaştırıyor', why: 'Turuncu düşük blokta (Kuyu önünde, 1 kişi basıyor). Mavi Kuyu önünde Çekirdeği dolaştırıyor. Beklenen: araya girme ya da ikili mücadeleyle Çekirdeği kazanmak, Kuyu önünü kapalı tutmak.', ch: .4, tac: [{}, { blok: 'Düşük', pres: 1, arkada: 1 }],
      ps: () => [P(0, 'Taşıyıcı', 66, 25), P(0, 'Sol kanat', 72, 8), P(0, 'Sağ kanat', 72, 42), P(0, 'Uç', 82, 22), P(0, 'Orta', 70, 32), P(0, 'Bek', 55, 18), P(0, 'Bizim Bekçi', 3, 25, 'Bekçi'), P(1, 'Savunma 1', 80, 18), P(1, 'Savunma 2', 80, 30), P(1, 'Savunma 3', 86, 25), P(1, 'Orta 1', 74, 20), P(1, 'Orta 2', 74, 30), P(1, 'Kanatçı', 78, 40), bek()] },
    { id: 'd2', group: 'Savunma', title: 'Orta blok · kanattan giriş', why: 'Turuncu orta blokta. Mavi sağ kanattan ilerliyor. Beklenen: kanattaki taşıyıcıyı yalnız bırakmamak, iç pas hatlarını kapatmak, çizgiye sıkıştırıp kazanmak.', ch: .4, tac: [{}, { blok: 'Orta', pres: 1, arkada: 1 }],
      ps: () => [P(0, 'Taşıyıcı', 60, 42), P(0, 'İç', 64, 30), P(0, 'Uç', 72, 22), P(0, 'Sol kanat', 62, 10), P(0, 'Orta', 52, 28), P(0, 'Bek', 45, 38), P(0, 'Bizim Bekçi', 3, 25, 'Bekçi'), P(1, 'Kanat savunma', 66, 40), P(1, 'Orta 1', 66, 28), P(1, 'Orta 2', 64, 18), P(1, 'Stoper 1', 76, 30), P(1, 'Stoper 2', 76, 20), P(1, 'Sol', 72, 10), bek()] },
    { id: 'd3', group: 'Savunma', title: 'Yüksek pres · rakip geriden kuruyor', why: 'Turuncu önde basıyor (3 kişi, yüksek blok). Mavi kendi yarı sahasında, geriden çıkmaya çalışıyor. Beklenen: pres hatları kapatsın, Çekirdeği rakip yarı sahada kazansın; ama arkada açık kalırsa bedeli olsun.', ch: .4, tac: [{}, { blok: 'Yüksek', pres: 3, arkada: 1 }],
      ps: () => [P(0, 'Taşıyıcı', 22, 25), P(0, 'Sol bek', 25, 8), P(0, 'Sağ bek', 25, 42), P(0, 'Pivot', 34, 25), P(0, 'Orta', 42, 15), P(0, 'Uç', 52, 30), P(0, 'Bizim Bekçi', 3, 25, 'Bekçi'), P(1, 'Presçi 1', 30, 22), P(1, 'Presçi 2', 32, 32), P(1, 'Presçi 3', 38, 15), P(1, 'Orta', 44, 28), P(1, 'Stoper', 58, 25), P(1, 'Kanat', 44, 42), bek()] },
    { id: 'd4', group: 'Savunma', title: 'Kuyu önü · son çizgi', why: 'Mavi Kuyu\'ya 20 birimde, iki arkadaşı koşuda. Turuncu az sayıda geride. Beklenen: göndermeyi kapatmak (Kuyu tarafına geçmek), koşucuları takip etmek, gerekirse taşıyıcıya çıkmak.', ch: .5, tac: [{}, { blok: 'Orta', pres: 1, arkada: 1 }],
      ps: () => [P(0, 'Taşıyıcı', 78, 25), P(0, 'Koşucu 1', 82, 14), P(0, 'Koşucu 2', 82, 36), P(0, 'Destek', 70, 30), P(0, 'Kanat', 70, 8), P(0, 'Bek', 60, 25), P(0, 'Bizim Bekçi', 3, 25, 'Bekçi'), P(1, 'Stoper 1', 86, 22), P(1, 'Stoper 2', 86, 30), P(1, 'Geri koşan', 74, 20), P(1, 'Orta', 68, 26), P(1, 'Kanat', 76, 40), P(1, 'Uzak', 62, 12), bek()] },
    { id: 'p1', group: 'Pres kırma', title: 'İki kişilik pres · arkası boş', why: 'Taşıyıcıya iki rakip basıyor. Presçilerin arkasında iki arkadaş boşta. Beklenen: presin arkasına (hatta tek dokunuşla) oynamak; pres kırılınca boşluğa ilerlemek.', ch: .4, tac: [{}, { blok: 'Yüksek', pres: 3, arkada: 1 }],
      ps: () => [P(0, 'Taşıyıcı', 30, 25), P(0, 'Arka sol', 45, 15), P(0, 'Arka sağ', 45, 35), P(0, 'Geride', 20, 22), P(0, 'İleri', 56, 25), P(0, 'Bek', 24, 40), P(0, 'Bizim Bekçi', 3, 25, 'Bekçi'), P(1, 'Presçi 1', 33, 22), P(1, 'Presçi 2', 33, 29), P(1, 'Presçi 3', 40, 14), P(1, 'Orta', 58, 18), P(1, 'Stoper', 64, 30), P(1, 'Arka', 72, 25), bek()] },
    { id: 'p2', group: 'Pres kırma', title: 'Kanatta sıkıştırma', why: 'Taşıyıcı çizgiye yakın, iki rakip onu kenara sıkıştırıyor. İçeride ve çizgi boyunca arkadaşlar var. Beklenen: kenardan sektirme, içeri pas ya da çizgi boyunca presin arkasına.', ch: .4, tac: [{}, { blok: 'Yüksek', pres: 3, arkada: 1 }],
      ps: () => [P(0, 'Taşıyıcı', 28, 44), P(0, 'İçeride', 38, 34), P(0, 'Çizgide', 44, 46), P(0, 'Geride', 20, 36), P(0, 'Orta', 40, 22), P(0, 'İleri', 58, 30), P(0, 'Bizim Bekçi', 3, 25, 'Bekçi'), P(1, 'Presçi 1', 31, 42), P(1, 'Presçi 2', 27, 40), P(1, 'Presçi 3', 36, 30), P(1, 'Orta', 50, 26), P(1, 'Stoper', 62, 30), P(1, 'Arka', 70, 22), bek()] },
    { id: 'p3', group: 'Pres kırma', title: 'Tek presçi · geçme fırsatı', why: 'Tek bir rakip taşıyıcıya geliyor, arkası 20 birim boş. Beklenen: presçiyi geçip (ya da yanından sürüp) önündeki koridoru kullanmak, ya da presçi gelmeden yanındaki arkadaşa verip koşmak.', ch: .4, tac: [{}, { blok: 'Yüksek', pres: 3, arkada: 1 }],
      ps: () => [P(0, 'Taşıyıcı', 35, 25), P(0, 'Sol', 42, 10), P(0, 'Sağ', 42, 40), P(0, 'Geride', 24, 28), P(0, 'İleri', 62, 22), P(0, 'Bek', 28, 12), P(0, 'Bizim Bekçi', 3, 25, 'Bekçi'), P(1, 'Presçi', 39, 25), P(1, 'Kanat 1', 50, 10), P(1, 'Kanat 2', 50, 40), P(1, 'Orta', 60, 30), P(1, 'Stoper', 68, 24), P(1, 'Arka', 76, 26), bek()] },
    { id: 'c1', group: 'Kontra', title: 'Arkada tek kişi', why: 'Rakip 5 kişiyle bizim yarımızda hücum ederken Çekirdeği kazandık. Arkalarında tek stoper var. Beklenen: hızla ileri oynamak (sürme, presin arkasına pas, öndeki koşucuya), stoper yerleşmeden göndermeye ulaşmak.', ch: .3, tac: [{ kazaninca: 'Kontra' }, { pres: 2, arkada: 1, blok: 'Yüksek' }],
      ps: () => [P(0, 'Kazanan', 24, 26), P(0, 'Yan', 30, 12), P(0, 'Orta', 36, 34), P(0, 'Koşucu', 48, 20), P(0, 'Geride', 14, 30), P(0, 'Bek', 18, 42), P(0, 'Bizim Bekçi', 3, 25, 'Bekçi'), P(1, 'Hücumcu 1', 22, 22), P(1, 'Hücumcu 2', 18, 32), P(1, 'Hücumcu 3', 28, 38), P(1, 'Hücumcu 4', 32, 16), P(1, 'Hücumcu 5', 38, 28), P(1, 'Stoper', 66, 24), bek()] },
    { id: 'c2', group: 'Kontra', title: 'Arkada iki kişi', why: 'Aynı an, ama rakip arkada iki kişi bırakmış. Beklenen: üçe iki ya da ikiye iki kurmak; iki savunmacıyı ikileme sokmak.', ch: .3, tac: [{ kazaninca: 'Kontra' }, { pres: 2, arkada: 2, blok: 'Yüksek' }],
      ps: () => [P(0, 'Kazanan', 24, 26), P(0, 'Yan', 30, 12), P(0, 'Orta', 36, 34), P(0, 'Koşucu', 48, 20), P(0, 'Geride', 14, 30), P(0, 'Bek', 18, 42), P(0, 'Bizim Bekçi', 3, 25, 'Bekçi'), P(1, 'Hücumcu 1', 22, 22), P(1, 'Hücumcu 2', 18, 32), P(1, 'Hücumcu 3', 28, 38), P(1, 'Hücumcu 4', 34, 18), P(1, 'Stoper 1', 62, 18), P(1, 'Stoper 2', 64, 32), bek()] },
    { id: 'c3', group: 'Kontra', title: 'Kanatta kazanma', why: 'Çekirdek çizgi kenarında kazanıldı, rakip o tarafa yığılı. Karşı taraf boş. Beklenen: önce yığından çıkmak (geri ya da içeri pas), sonra boş tarafa hızla ilerlemek.', ch: .3, tac: [{ kazaninca: 'Kontra' }, { pres: 2, arkada: 1, blok: 'Yüksek' }],
      ps: () => [P(0, 'Kazanan', 26, 44), P(0, 'İçeride', 32, 32), P(0, 'Karşı', 40, 12), P(0, 'Koşucu', 50, 26), P(0, 'Geride', 16, 34), P(0, 'Bek', 14, 18), P(0, 'Bizim Bekçi', 3, 25, 'Bekçi'), P(1, 'Hücumcu 1', 24, 40), P(1, 'Hücumcu 2', 30, 46), P(1, 'Hücumcu 3', 20, 36), P(1, 'Hücumcu 4', 34, 38), P(1, 'Hücumcu 5', 36, 24), P(1, 'Stoper', 64, 26), bek()] },
    { id: 'c4', group: 'Kontra', title: 'Kuyu önünde kazanma', why: 'Rakip bizim Kuyu önüne yığılmışken Çekirdeği 12 birimde kazandık. Arkalarında iki kişi 55-60 civarında. Beklenen: önce kalabalıktan güvenli çıkış, sonra koşuculara.', ch: .3, tac: [{ kazaninca: 'Kontra' }, { pres: 2, arkada: 2, blok: 'Yüksek' }],
      ps: () => [P(0, 'Kazanan', 12, 22), P(0, 'Yan', 16, 36), P(0, 'Orta', 26, 18), P(0, 'Koşucu', 36, 30), P(0, 'Kanat', 30, 6), P(0, 'Bek', 10, 40), P(0, 'Bizim Bekçi', 3, 25, 'Bekçi'), P(1, 'Hücumcu 1', 14, 26), P(1, 'Hücumcu 2', 10, 16), P(1, 'Hücumcu 3', 20, 32), P(1, 'Hücumcu 4', 22, 14), P(1, 'Stoper 1', 55, 20), P(1, 'Stoper 2', 60, 32), bek()] },
    { id: 'c5', group: 'Kontra', title: 'Orta sahada kesme · üçe iki', why: 'Çekirdek orta sahada kesildi. Önümüzde iki savunmacı, yanımızda iki koşucu. Beklenen: savunmacıları ikileme sokup boştakini kullanmak.', ch: .3, tac: [{ kazaninca: 'Kontra' }, { pres: 2, arkada: 2, blok: 'Yüksek' }],
      ps: () => [P(0, 'Kazanan', 48, 25), P(0, 'Sol', 50, 12), P(0, 'Sağ', 50, 38), P(0, 'Destek', 40, 30), P(0, 'Geride', 28, 22), P(0, 'Bek', 24, 38), P(0, 'Bizim Bekçi', 3, 25, 'Bekçi'), P(1, 'Hücumcu 1', 46, 28), P(1, 'Hücumcu 2', 42, 18), P(1, 'Hücumcu 3', 36, 34), P(1, 'Hücumcu 4', 34, 14), P(1, 'Stoper 1', 70, 20), P(1, 'Stoper 2', 72, 31), bek()] },
    { id: 'c6', group: 'Kontra', title: 'Tek forvet · uzun aşırtma', why: 'Derinde kazandık, tek forvetimiz rakibin son adamıyla bire bir. Arada kimse yok. Beklenen: uzun aşırtmayla forvetin önüne, ya da destek gelene kadar tutmak.', ch: .3, tac: [{ kazaninca: 'Kontra' }, { pres: 2, arkada: 1, blok: 'Yüksek' }],
      ps: () => [P(0, 'Kazanan', 18, 25), P(0, 'Forvet', 66, 22), P(0, 'Yan', 22, 10), P(0, 'Orta', 26, 36), P(0, 'Geride', 10, 30), P(0, 'Bek', 14, 42), P(0, 'Bizim Bekçi', 3, 25, 'Bekçi'), P(1, 'Hücumcu 1', 20, 30), P(1, 'Hücumcu 2', 24, 18), P(1, 'Hücumcu 3', 30, 28), P(1, 'Hücumcu 4', 28, 40), P(1, 'Hücumcu 5', 34, 12), P(1, 'Stoper', 72, 25), bek()] },
    { id: 'c7', group: 'Kontra', title: 'Rakip hazırlıklı · arkada üç kişi', why: 'Kazandık ama rakip arkada üç kişi bırakmış. Kontra kapalı. Beklenen: zorlamamak; Kontra talimatında bile hızlı ama güvenli oynamak ya da tutmak.', ch: .3, tac: [{ kazaninca: 'Kontra' }, { pres: 1, arkada: 2, blok: 'Orta' }],
      ps: () => [P(0, 'Kazanan', 30, 25), P(0, 'Yan', 36, 10), P(0, 'Orta', 40, 34), P(0, 'Koşucu', 50, 22), P(0, 'Geride', 20, 30), P(0, 'Bek', 22, 42), P(0, 'Bizim Bekçi', 3, 25, 'Bekçi'), P(1, 'Hücumcu 1', 28, 21), P(1, 'Hücumcu 2', 34, 30), P(1, 'Hücumcu 3', 38, 16), P(1, 'Stoper 1', 62, 14), P(1, 'Stoper 2', 64, 26), P(1, 'Stoper 3', 62, 38), bek()] },
    { id: 'c8', group: 'Kontra', title: 'Hızlı geri dönen rakip', why: 'Rakip öndeydi ama hücumcuları kazandığımız noktaya yakın değil, Kuyularına dönüyorlar. Pencere kısa. Beklenen: ilk 1-2 saniyede tek dokunuşla ileri; pencere kapanınca yerleşik hücuma geçmek.', ch: .3, tac: [{ kazaninca: 'Kontra' }, { pres: 1, arkada: 1, blok: 'Orta' }],
      ps: () => [P(0, 'Kazanan', 34, 25), P(0, 'Yan', 40, 10), P(0, 'Orta', 42, 36), P(0, 'Koşucu', 52, 26), P(0, 'Geride', 24, 22), P(0, 'Bek', 26, 40), P(0, 'Bizim Bekçi', 3, 25, 'Bekçi'), P(1, 'Hücumcu 1', 40, 20, null, { vx: .3 }), P(1, 'Hücumcu 2', 42, 32), P(1, 'Hücumcu 3', 46, 14), P(1, 'Hücumcu 4', 48, 38), P(1, 'Orta', 58, 26), P(1, 'Stoper', 68, 24), bek()] }
  ];
  // Bekçi maçtaki gibi yerleşir: Kuyu'dan taşıyıcıya doğru, Çekirdek–Kuyu hattında
  function place(ps) { const h = ps[0], gx = h.team === 0 ? 100 : 0; for (const p of ps) if (p.role === 'Bekçi' && p.team !== h.team) { const dx = h.x - gx, dy = h.y - 25, L = Math.hypot(dx, dy) || 1, r = Math.min(6, L * .22); p.x = gx + dx / L * r; p.y = 25 + dy / L * r; } return ps; }

  // Pozisyon oynatma (her sahne oyuncusu derinlik ve kanat olarak en yakın görevi alır): sahnedeki oyuncular gerçek maç motoruna konur, hücum bitene kadar oynanır (sayı, kayıp ya da 6 sn)
  function play(sc, seed, okuma, maxT) {
    const M = window.AlanMatch, m = M.createMatch(seed, sc.tac ? { tac: sc.tac } : {}), sp = place(sc.ps()), used = new Set(), out = []; if (sc.group === 'Kontra') { m.winT = 0; m.winTeam = 0; }
    for (const s of sp) { const pool = m.ps.filter(p => p.team === s.team && !used.has(p)); const p = s.role === 'Bekçi' ? pool.find(p => p.role === 'Bekçi') : pool.filter(p => p.role !== 'Bekçi').sort((u, v) => (Math.abs(u.slot.d - s.x / 100) + Math.abs(u.slot.l - (s.y - 25) / 22)) - (Math.abs(v.slot.d - s.x / 100) + Math.abs(v.slot.l - (s.y - 25) / 22)))[0]; used.add(p); p.x = p.tx = s.x; p.y = p.ty = s.y; p.vx = p.vy = 0; p.name = s.name; Object.assign(p.a, s.a); if (okuma != null && s === sp[0]) p.a.okuma = okuma; out.push(p); }
    m.ps = out; m.holder = out[0]; m.ball = null; m.ch = sc.ch; m.decT = 1; m.fl = null;
    let res = 'süre'; const frames = [];
    for (let t = 0; t < (maxT || 360); t++) { try { M.step(m); } catch (e) {} frames.push({ ps: m.ps.map(p => [p.x, p.y]), tg: m.ps.map(p => [p.tx, p.ty]), job: m.ps.map(p => p.job || ''), b: m.holder ? [m.holder.x, m.holder.y] : m.ball ? [m.ball.x, m.ball.y] : null, air: !m.holder && m.ball ? m.ball.air || 0 : 0 });
      if (m.score[0] > 0) { res = 'SAYI'; break; } if (m.score[1] > 0) { res = 'kendi Kuyu'; break; }
      if (m.holder && m.holder.team === 1) { res = m.holder.role === 'Bekçi' ? 'Bekçi aldı' : 'kaybetti'; break; } }
    return { res, shots: m.st.shot[0], passes: m.st.pass[0], events: m.events.slice().reverse(), frames, names: m.ps.map(p => p.name), teams: m.ps.map(p => p.team) };
  }
  function run(sc, N, okuma) {
    const D = window.AlanDecide, rnd = (s => () => { s = (s * 1664525 + 1013904223) >>> 0; return s / 4294967296; })(7), out = {};
    let pred = 0, real = 0, n = 0, last = null;
    for (let i = 0; i < N; i++) {
      const ps = place(sc.ps()); const h = ps[0]; if (okuma != null) h.a.okuma = okuma;
      const r = D.decide(h, ps, sc.ch, rnd, null), b = r.best; out[b.kind] = (out[b.kind] || 0) + 1; last = r;
      if (b.launch) { const re = D.realize(h, b, ps, sc.ch, rnd); const good = b.kind === 'gönder' ? re.res === 'kuyu' : re.res === 'mate'; pred += b.kind === 'gönder' ? b.det.Pk : b.det.P; real += good ? 1 : 0; n++; }
    }
    const top = Object.entries(out).sort((a, b) => b[1] - a[1])[0][0];
    const lowOk = sc.needOk && (okuma ?? 10) < sc.needOk, okExp = lowOk ? top !== 'kenardan' : sc.expect.includes(top) && !(sc.forbid || []).some(k => (out[k] || 0) > N * .2);
    return { dist: out, top, pass: okExp, pred: n ? pred / n : null, real: n ? real / n : null, n, last };
  }
  window.AlanScenes = { S, run, P, A, place, play };
})();
