// v5 maç işçisi: v3d motoru. Maçı izlemenin önünde oynar, kareleri sayfaya gönderir. Taktik değişince maç baştan aynı tohumla, değişiklik geçmişiyle yeniden oynanır (v3d'de kopya yok; motor belirlenimci).
self.window = self;
importScripts('core.js', 'shot-table.js', 'value-table.js', 'decide.js', 'match.js', 'shape.js');
const M = self.AlanMatch, NF = 34; let gen = 0, m = null, len = 5400, kur = null, gecmis = [], buf = null, sonDec = null;
const yeniBuf = () => ({ kare: [], olay: [], karar: [] });
function statik(m) { return m.ps.map(p => ({ id: p.id, name: p.name, role: p.role, team: p.team, a: { ...p.a }, R: p.R, D: p.D, i: p.i })); }
function kaydet(m) { const f = new Float32Array(NF); m.ps.forEach((p, k) => { f[2 * k] = p.x; f[2 * k + 1] = p.y; }); const c = M.corePos(m); f[28] = c ? c.x : NaN; f[29] = c ? c.y : NaN; f[30] = m.holder ? m.ps.indexOf(m.holder) : -1; f[31] = m.holder ? m.ch : (m.ball ? m.ball.ch || 0 : 0); f[32] = m.score[0]; f[33] = m.score[1]; buf.kare.push([m.tick, f]);
  if (m.events.length && m.events[0] !== m._sonOlay) { let k = 0; while (k < m.events.length && m.events[k] !== m._sonOlay) k++; for (let j = k - 1; j >= 0; j--) buf.olay.push({ tick: m.tick, ...m.events[j] }); m._sonOlay = m.events[0]; }
  const d = m.lastDec; if (d && d !== sonDec) { sonDec = d; const h = m.ps.find(p => p.name === d.name); buf.karar.push({ tip: 'karar', tick: m.tick, ad: d.name, team: d.team, okuma: h ? h.a.okuma : null, x: d.x, y: d.y, aday: d.opts.map(o => ({ kind: o.kind + (o.q ? ' → ' + o.q : ''), v: +(o.v || 0).toFixed(3), p: o.P == null ? 0 : +o.P.toFixed(2), to: o.to ? { x: o.to.x, y: o.to.y } : null })), secilen: 0 }); } }
function gonder(g, son) { postMessage({ tip: 'kare', gen: g, kare: buf.kare, olay: buf.olay, karar: buf.karar, tick: m.tick, son: !!son }); buf = yeniBuf(); }
function uygula(m, c) { m.tac[c.t] = { ...m.tac[c.t], ...c.tac }; if (c.diz) M.dizUygula(m, c.t, c.diz); }
function yeniden(T) { m = M.createMatch(kur.tohum, { tac: kur.tac, len, diz: kur.diz }); if (kur.oz === 'rastgele') rastgele(m); kurUygula(m, kur); let ci = 0; while (m.tick < T && !m.over) { while (ci < gecmis.length && gecmis[ci].tick <= m.tick) uygula(m, gecmis[ci++]); M.step(m); } while (ci < gecmis.length && gecmis[ci].tick <= m.tick) uygula(m, gecmis[ci++]); m._sonOlay = m.events[0]; sonDec = m.lastDec; }
// Menajer kurulumu: hangi oyuncu hangi sırada (diziliş yeri), özellikleri, rolleri. Diziliş en son yeniden uygulanır: yeri diziliş, davranışı rol belirler.
function kurUygula(m, d) { if (d.oyuncular) for (const t of [0, 1]) { const A = d.oyuncular[t]; if (!A) continue; for (const p of m.ps) { if (p.team !== t) continue; const o = A[p.i]; if (o) { p.name = o.ad; p.a = { ...p.a, ...o.a }; } } } if (d.roller) M.assignRoles(m, d.roller); if (d.diz) for (const t of [0, 1]) if (d.diz[t]) M.dizUygula(m, t, d.diz[t]); }
function rastgele(m) { let r0 = kur.kadro * 2654435761 >>> 0; const R = () => (r0 = (Math.imul(r0, 1664525) + 1013904223) >>> 0) / 4294967296; for (const p of m.ps) for (const k of Object.keys(p.a)) p.a[k] = 6 + Math.floor(R() * 11); }
async function calistir(g) { try { while (!m.over && m.tick < len) { M.step(m); if (g !== gen) return; kaydet(m); if (m.tick % 60 === 0) { gonder(g); await new Promise(r => setTimeout(r, 0)); if (g !== gen) return; } } } catch (e) { postMessage({ tip: 'hata', msg: String(e && e.stack || e) }); return; } if (g === gen) gonder(g, true); }
onmessage = e => { const d = e.data;
  if (d.tip === 'yeni') { gen = d.gen; len = d.len; kur = d; gecmis = []; m = M.createMatch(d.tohum, { tac: d.tac, len, diz: d.diz }); if (d.oz === 'rastgele') rastgele(m); kurUygula(m, d); buf = yeniBuf(); sonDec = null; kaydet(m); postMessage({ tip: 'basla', gen, ps: statik(m) }); calistir(gen); return; }
  if (d.tip === 'degistir') { gen = d.gen; gecmis = gecmis.filter(c => c.tick < d.snapT); gecmis.push({ tick: d.snapT, t: d.t, tac: d.tac, diz: d.diz }); yeniden(d.snapT); buf = yeniBuf(); calistir(gen); } };
