// 8. madde raporu: lab/ab/e2 (yoksa e1) ve lab/ab/mac, lab/ab/S özetleri
const fs = require('fs'), L = 'lab/ab'; const kl = fs.existsSync(L + '/e2') && fs.readdirSync(L + '/e2').length ? L + '/e2' : L + '/e1';
const R = fs.readdirSync(kl).map(f => fs.readFileSync(kl + '/' + f, 'utf8').trim()).filter(Boolean).map(l => JSON.parse(l)).filter(r => !r.hata);
const avg = a => a.length ? a.reduce((s, x) => s + x, 0) / a.length : NaN, se = a => { const m = avg(a); return Math.sqrt(a.reduce((s, x) => s + (x - m) ** 2, 0) / Math.max(1, a.length - 1) / a.length); };
const f3 = x => (x >= 0 ? '+' : '') + x.toFixed(3), YON = ['C', 'S', 'Sx', 'B', 'A0', 'A', 'CA0', 'CA', 'K'].filter(y => R.some(r => r.yon[y]));
const AD = { C: 'C · ilk bakış (arama kapalı)', S: 'S · şimdiki arama (gerçek seçimi)', Sx: 'S · şimdiki arama (en yüksek değer)', B: 'B · hücum sonuna kadar oynatma', A0: 'A0 · arama + yeniden öğrenilen tablo (eski boyutlar)', A: 'A · arama + öğrenilen tablo (+ açıklık, boş arkadaş)', CA0: 'ilk bakış + A0 tablosu', CA: 'ilk bakış + A tablosu', K: 'kâhinin seçimi (6 denemeyle seçilip 30 denemeyle ölçülen)' };
const val = (r, k) => avg(r.aday[k].k), out = [];
out.push(`anlar: ${R.length} (${kl}) · ortalama aday ${avg(R.map(r => r.aday.length)).toFixed(0)}`);
out.push('\n## Seçilen hamlenin kâhin değeri (30 deneme, hücum sonuna kadar)\n| yöntem | ortalama | C\'ye göre (eşli) | kâhin seçimine göre kayıp | süre (ms/karar, tek çekirdek) |\n|---|---|---|---|---|');
for (const y of YON) { const rr = R.filter(r => r.yon[y] && r.yon.C && r.yon.K), v = rr.map(r => val(r, r.yon[y].k)), dC = rr.map(r => val(r, r.yon[y].k) - val(r, r.yon.C.k)), dK = rr.map(r => val(r, r.yon.K.k) - val(r, r.yon[y].k)), ms = rr.map(r => r.yon[y].ms).filter(x => x != null);
  out.push(`| ${AD[y]} | ${f3(avg(v))} ± ${se(v).toFixed(3)} | ${f3(avg(dC))} ± ${se(dC).toFixed(3)} | ${f3(avg(dK))} | ${ms.length ? Math.round(avg(ms)) : '–'} |`); }
// iyimser üst sınır: her anda adayların 6 denemelik ortalamasının en büyüğü (seçim yanlılığı içerir)
out.push(`\nüst sınır (iyimser, 6 denemelik en büyük): ${f3(avg(R.map(r => Math.max(...r.aday.map(a => avg(a.k.slice(0, 6)))))))} · anın aday ortalaması: ${f3(avg(R.map(r => avg(r.aday.map(a => avg(a.k.slice(0, 6)))))))}`);
// gürültü tabanı
{ const h1 = [], h2 = []; for (const r of R) for (const k of new Set(Object.values(r.yon).map(y => y.k))) { const a = r.aday[k].k; if (a.length >= 30) { h1.push(avg(a.slice(0, 15))); h2.push(avg(a.slice(15, 30))); } }
  const cor = (a, b) => { const ma = avg(a), mb = avg(b); let s = 0, sa = 0, sb = 0; for (let i = 0; i < a.length; i++) { s += (a[i] - ma) * (b[i] - mb); sa += (a[i] - ma) ** 2; sb += (b[i] - mb) ** 2; } return s / Math.sqrt(sa * sb); };
  let ag = 0, n = 0, ib = 0; const wc = []; for (const r of R) { const A1 = r.aday.map(a => avg(a.k.slice(0, 3))), A2 = r.aday.map(a => avg(a.k.slice(3, 6))); wc.push(cor(A1, A2)); const i1 = A1.indexOf(Math.max(...A1)), i2 = A2.indexOf(Math.max(...A2)); n++; if (i1 === i2) ag++; ib += A2[i1] - avg(A2); }
  let sg = 0, sn = 0; for (const r of R) { const a = r.aday[r.yon.S.k].k, c = r.aday[r.yon.C.k].k; if (r.yon.S.k === r.yon.C.k) continue; const d1 = avg(a.slice(0, 15)) - avg(c.slice(0, 15)), d2 = avg(a.slice(15, 30)) - avg(c.slice(15, 30)); if (d1 && d2) { sn++; if (Math.sign(d1) === Math.sign(d2)) sg++; } }
  out.push(`\n## Gürültü tabanı (iki bağımsız kâhin)\n- seçilen hamleler, 15'er denemelik iki yarı: ilişki r = ${cor(h1, h2).toFixed(2)} (n ${h1.length})\n- bütün adaylar, 3'er denemelik iki yarı: anın içinde ilişki ortalaması r = ${avg(wc.filter(Number.isFinite)).toFixed(2)} · iki yarının en iyisi aynı aday: %${(100 * ag / n).toFixed(0)} · birinci yarının en iyisinin ikinci yarıdaki üstünlüğü (anın ortalamasına göre): ${f3(ib / n)}\n- S ile C farklı seçtiğinde farkın işareti iki yarıda aynı: %${(100 * sg / sn).toFixed(0)} (n ${sn}; rastgele %50)`); }
// sınıflar
const SIN = ['geri/yan pas', 'bekle', 'kanat değiştir', 'ileri pas', 'sür', 'sür geri', 'tut', 'gönder'];
out.push('\n## Hamle türleri: seçilme oranı (%) ve seçildiğinde kâhin değeri\n| yöntem | ' + SIN.join(' | ') + ' | 35+ gönderme |\n|' + '---|'.repeat(SIN.length + 2));
for (const y of YON) { const rr = R.filter(r => r.yon[y]); out.push(`| ${y} | ` + SIN.map(s => { const q = rr.filter(r => r.aday[r.yon[y].k].s === s); return q.length ? `${(100 * q.length / rr.length).toFixed(0)} (${f3(avg(q.map(r => val(r, r.yon[y].k))))})` : '0'; }).join(' | ') + ` | ${(100 * rr.filter(r => r.aday[r.yon[y].k].s === 'gönder' && r.aday[r.yon[y].k].uz >= 35).length / rr.length).toFixed(0)} |`); }
out.push('\nTürün kâhin değeri, aynı anın aday ortalamasına göre (bütün adaylar, 6 deneme) ve S değerine göre (aramanın kendi tahmini, anın ortalamasına göre):\n| tür | aday sayısı | kâhin − an ortalaması | S tahmini − an ortalaması |\n|---|---|---|---|');
for (const s of SIN) { const k = [], sv = []; for (const r of R) { const mk = avg(r.aday.map(a => avg(a.k.slice(0, 6)))), ms = avg(r.aday.filter(a => a.sv != null).map(a => a.sv)); for (const a of r.aday) if (a.s === s) { k.push(avg(a.k.slice(0, 6)) - mk); if (a.sv != null) sv.push(a.sv - ms); } } out.push(`| ${s} | ${k.length} | ${f3(avg(k))} | ${f3(avg(sv))} |`); }
// arama değeri kâhini ne kadar tahmin ediyor
{ const cs = [], cb = []; const cor = (a, b) => { const ma = avg(a), mb = avg(b); let s = 0, sa = 0, sb = 0; for (let i = 0; i < a.length; i++) { s += (a[i] - ma) * (b[i] - mb); sa += (a[i] - ma) ** 2; sb += (b[i] - mb) ** 2; } return s / Math.sqrt(sa * sb); };
  for (const r of R) { const ix = r.aday.map((a, i) => i).filter(i => r.aday[i].sv != null && r.bv && r.bv[i] != null), K = ix.map(i => avg(r.aday[i].k.slice(0, 6))); cs.push(cor(ix.map(i => r.aday[i].sv), K)); cb.push(cor(ix.map(i => r.bv[i]), K)); }
  out.push(`\n## Tahmin gücü: anın içinde yöntemin aday değerleri ile kâhinin (6 deneme) ilişkisi\n- S (arama, ilk dalga + derinleştirme): r = ${avg(cs.filter(Number.isFinite)).toFixed(2)}\n- B (6 deneme): r = ${avg(cb.filter(Number.isFinite)).toFixed(2)}\n- (kâhinin kendi iki yarısı, yukarıda: tavan)`); }
// sahneler
out.push('\n## Sahneler (kâhin değeri, C\'ye göre eşli fark)\n| sahne | n | ' + YON.filter(y => y !== 'C').join(' | ') + ' |\n|' + '---|'.repeat(YON.length + 1));
for (const [ad, f] of [['pres kırma', r => r.sahne.pres], ['derin blok', r => r.sahne.derin], ['kanat değiştirme fırsatı', r => r.sahne.kanat], ['hepsi', () => true]]) { const rr = R.filter(f); out.push(`| ${ad} | ${rr.length} | ` + YON.filter(y => y !== 'C').map(y => { const q = rr.filter(r => r.yon[y]); return f3(avg(q.map(r => val(r, r.yon[y].k) - val(r, r.yon.C.k)))); }).join(' | ') + ' |'); }
// maçlar
const M = {}; const ekle = (y, o) => (M[y] = M[y] || []).push(o);
if (fs.existsSync(L + '/S')) for (const f of fs.readdirSync(L + '/S')) { const t = fs.readFileSync(L + '/S/' + f, 'utf8').trim(); if (t) ekle('S', JSON.parse(t)); }
if (fs.existsSync(L + '/mac')) for (const f of fs.readdirSync(L + '/mac')) { const t = fs.readFileSync(L + '/mac/' + f, 'utf8').trim(); if (t) { const o = JSON.parse(t); ekle(o.yon, o); } }
out.push('\n## 10\'ar maç (Herkes 10, aynı tohumlar ve taktikler; değerler maç başına, iki takım toplamı)\n| yöntem | maç | kendi yarıda topla (sn) | 35+ gönderme | gönderme | pas tutma | sayı/maç | süre/maç (tek çekirdek, sn) |\n|---|---|---|---|---|---|---|---|');
for (const y of ['C', 'S', 'A0', 'A', 'B']) { const a = M[y]; if (!a) continue; out.push(`| ${y} | ${a.length} | ${avg(a.map(o => o.kendiYariSn)).toFixed(1)} | ${avg(a.map(o => o.gon35)).toFixed(1)} | ${avg(a.map(o => o.gon)).toFixed(1)} | %${(100 * a.reduce((s, o) => s + o.pasOk, 0) / a.reduce((s, o) => s + o.pas, 0)).toFixed(0)} | ${avg(a.map(o => o.sayi)).toFixed(1)} ± ${se(a.map(o => o.sayi)).toFixed(1)} | ${avg(a.map(o => o.sn)).toFixed(0)}${y === 'B' ? ' (karar başına ' + avg(a.map(o => o.bMs)).toFixed(0) + ' ms)' : ''} |`); }
console.log(out.join('\n'));
