// davranis.js çıktısını hücre × taktik (A/B) olarak özetler.
const rows = require('fs').readFileSync(process.argv[2], 'utf8').trim().split('\n').map(JSON.parse);
const f = (v, d = 1) => v == null || isNaN(v) ? '–' : v.toFixed(d), pc = v => isNaN(v) ? '–' : '%' + Math.round(v * 100), avg = a => a.length ? a.reduce((s, x) => s + x, 0) / a.length : NaN;
for (const cell of [...new Set(rows.map(r => r.cell))]) {
  const rs = rows.filter(r => r.cell === cell), n = rs.length; console.log(`\n=== ${cell} · ${n} maç · skor A ${rs.reduce((s, r) => s + r.score.A, 0)} – B ${rs.reduce((s, r) => s + r.score.B, 0)}`);
  for (const k of ['A', 'B']) { const X = rs.map(r => r.R[k]), all = key => X.flatMap(x => x[key]);
    const dec = {}; for (const x of X) for (const [a, b] of Object.entries(x.dec)) dec[a] = (dec[a] || 0) + b; const dt = Object.values(dec).reduce((a, b) => a + b, 0);
    console.log(`\n-- ${k} · kararlar (${f(dt / n, 0)}/maç): ` + Object.entries(dec).sort((a, b) => b[1] - a[1]).map(([a, b]) => `${a} ${pc(b / dt)}`).join(', '));
    const dz = {}; for (const x of X) for (const [a, b] of Object.entries(x.decZone)) dz[a] = (dz[a] || 0) + b;
    for (const z of ['kendi', 'orta', 'rakip']) { const e = Object.entries(dz).filter(([a]) => a.startsWith(z + ':')), t = e.reduce((s, [, b]) => s + b, 0); console.log(`   ${z} üçte bir (${t}): ` + e.sort((a, b) => b[1] - a[1]).map(([a, b]) => `${a.split(':')[1]} ${pc(b / t)}`).join(', ')); }
    const L = all('launch'); const kinds = [...new Set(L.map(l => l.kind))];
    console.log(`   paslar ${f(L.length / n, 1)}/maç:`); for (const kd of kinds) { const a = L.filter(l => l.kind === kd), ok = a.filter(l => l.res === 'tuttu').length, wp = a.filter(l => l.P != null);
      console.log(`     ${kd.padEnd(9)} ${f(a.length / n, 1).padStart(5)}/maç · tutma ${pc(ok / a.length)} (tahmin ${pc(avg(wp.map(l => l.P)))}) · mesafe ${f(avg(a.map(l => l.dist)))} · ileri ${pc(a.filter(l => l.fwd > 2).length / a.length)} geri ${pc(a.filter(l => l.fwd < -2).length / a.length)} · tek dokunuş ${pc(a.filter(l => l.ot).length / a.length)}`); }
    const mg = L.filter(l => l.margin != null).map(l => l.margin); console.log(`     karar farkı (en iyi − ikinci): medyan ${f(mg.sort((a, b) => a - b)[mg.length >> 1], 3)} · <0,005 olan ${pc(mg.filter(v => v < .005).length / mg.length)}`);
    const Sh = all('shots'), gl = Sh.filter(s => s.res === 'sayı').length; console.log(`   gönderme ${f(Sh.length / n, 1)}/maç · girme ${pc(gl / Sh.length)} (tahmin ${pc(avg(Sh.filter(s => s.P != null).map(s => s.P)))}) · Kuyu'ya uzaklık ${f(avg(Sh.map(s => s.gd)))} · ort. açı |y−25| ${f(avg(Sh.map(s => s.ang)))} · ${Sh.filter(s => s.gd < 12).length} yakın / ${Sh.filter(s => s.gd >= 12 && s.gd < 22).length} orta / ${Sh.filter(s => s.gd >= 22).length} uzak`);
    const P = all('poss'); console.log(`   hücum dizisi ${f(P.length / n, 1)}/maç · süre ${f(avg(P.map(p => p.dur / 60)))} sn · pas ${f(avg(P.map(p => p.passes)))} · göndermeyle biten ${pc(P.filter(p => p.shot).length / P.length)} · rakip üçte bire varan ${pc(P.filter(p => p.endZone === 'rakip' || p.shot).length / P.length)} · kazanarak başlayan ${pc(P.filter(p => p.how === 'kazanma').length / P.length)}`);
    const Pz = {}; for (const p of P.filter(p => p.how === 'kazanma')) Pz[p.startZone] = (Pz[p.startZone] || 0) + 1; console.log(`   top kazanılan yer: ` + Object.entries(Pz).map(([a, b]) => `${a} ${b}`).join(', '));
    const G = all('goals'); console.log(`   sayılar ${G.length}: ` + G.map(g => `${g.passes} pas/${f(g.dur / 60)} sn/${g.from}@${g.startZone}`).join(' · '));
    const D = all('snapD'); console.log(`   SAVUNMA: son çizgi ${f(avg(D.map(d => d.deep)))} · ön çizgi ${f(avg(D.map(d => d.high)))} · boy ${f(avg(D.map(d => d.len)))} · en ${f(avg(D.map(d => d.wid)))} · basan ${f(avg(D.map(d => d.press)), 2)} · topun 8 birimindeki savunmacı ${f(avg(D.map(d => d.near)), 2)} · 5 birimde savunmacısı olmayan hücumcu ${f(avg(D.map(d => d.unmarked)), 2)} · son çizginin arkasındaki hücumcu ${f(avg(D.map(d => d.behind)), 2)} · tehlikeli bölgede Kuyu tarafı tutulan ${pc(avg(D.filter(d => d.inDang).map(d => d.goalSide / d.inDang)))}`);
    for (const [lo, hi, nm] of [[0, 35, 'top kendi bölgemizde'], [35, 65, 'top ortada'], [65, 101, 'top rakip bölgede']]) { const d = D.filter(x => x.ballD >= lo && x.ballD < hi); console.log(`     ${nm} (${d.length}): son çizgi ${f(avg(d.map(x => x.deep)))} · boy ${f(avg(d.map(x => x.len)))} · basan ${f(avg(d.map(x => x.press)), 2)}`); }
    const Aa = all('snapA'); console.log(`   HÜCUM ŞEKLİ: en ${f(avg(Aa.map(a => a.wid)))} · boy ${f(avg(Aa.map(a => a.len)))} · depar atan ${f(avg(Aa.map(a => a.sprint)), 2)}`);
    const J = {}; for (const x of X) for (const [a, b] of Object.entries(x.jobs)) J[a] = (J[a] || 0) + b; for (const side of ['H:', 'S:']) { const e = Object.entries(J).filter(([a]) => a.startsWith(side)), t = e.reduce((s, [, b]) => s + b, 0); console.log(`   ${side === 'H:' ? 'hücumda işler' : 'savunmada işler'}: ` + e.sort((a, b) => b[1] - a[1]).slice(0, 9).map(([a, b]) => `${a.slice(2) || '(yok)'} ${pc(b / t)}`).join(', ')); }
  }
}
