// hareket.js ve savunma.js çıktılarının özeti (birden çok klasör yan yana). Kullanım: node tools/hs-ozet.js <hareket|savunma> <klasör>...
const fs = require('fs'), path = require('path'), [tip, ...dirs] = process.argv.slice(2);
const oku = d => fs.readdirSync(d).filter(f => f.endsWith('.json')).map(f => fs.readFileSync(path.join(d, f), 'utf8').trim()).filter(Boolean).map(JSON.parse);
const pc = (a, f) => a.length ? (100 * a.filter(f).length / a.length).toFixed(0) + '%' : '–', med = a => { a = a.slice().sort((x, y) => x - y); return a.length ? a[a.length >> 1] : '–'; };
for (const d of dirs) { const R = oku(d); console.log(`\n== ${d} (${R.length} maç)`);
  if (tip === 'hareket') { const dk = R.reduce((s, r) => s + r.oyuncuDk, 0), top = k => { const o = {}; for (const r of R) for (const [a, v] of Object.entries(r[k])) o[a] = (o[a] || 0) + v * r.oyuncuDk; return o; }, sum = o => Object.values(o).reduce((s, v) => s + v, 0) / dk;
    for (const k of ['donus', 'sicrama', 'ivme', 'durKalk']) { const o = top(k); console.log(`${k}: toplam ${sum(o).toFixed(0)} /oyuncu-dk · ` + Object.entries(o).sort((a, b) => b[1] - a[1]).map(([a, v]) => `${a} ${(v / dk).toFixed(1)}`).join(' · ')); } }
  else { const ik = R.flatMap(r => r.ikili).filter(x => x.kazandi != null), Y = R.reduce((s, r) => { for (const k in r.yer) s[k] = (s[k] || 0) + r.yer[k]; return s; }, {}), bas = R.flatMap(r => r.basinc), kay = R.flatMap(r => r.kayip);
    console.log(`skor ${R.map(r => r.skor.join('-')).join(' ')} · ikili fırsat ${R.reduce((s, r) => s + r.firsat, 0)}, girilen ${pc(R.flatMap(r => Array(r.firsat).fill(0).map((_, j) => j < r.girdi)), x => x)} · ikili ${ik.length}, savunmacı kazandı ${pc(ik, x => x.kazandi)} (P ort. ${(100 * ik.reduce((s, x) => s + x.P, 0) / ik.length).toFixed(0)}%)`);
    console.log(`korunuyor ${pc(ik.filter(x => x.korunuyor), x => x.kazandi)} (n=${ik.filter(x => x.korunuyor).length}) · korunmuyor ${pc(ik.filter(x => !x.korunuyor), x => x.kazandi)} · ` + ['top tarafından', 'yandan', 'gövde tarafından'].map(a => `${a} ${pc(ik.filter(x => x.aci === a), x => x.kazandi)} (n=${ik.filter(x => x.aci === a).length})`).join(' · ') + ` · ikinci presçi var ${pc(ik.filter(x => x.ikinci), x => x.kazandi)} / yok ${pc(ik.filter(x => !x.ikinci), x => x.kazandi)}`);
    console.log(`baskı altında kayba kadar: medyan ${med(kay)} tik, n=${kay.length} · ilk baskı medyanı ${med(bas.map(b => b.t))} tik`);
    console.log(`yerleşim: arada savunmacı ${(100 * Y.arada / Y.n).toFixed(0)}% · tehlikeli rakip boş ${(100 * Y.tehlikeBos / Y.n).toFixed(0)}% · üst üste ${(100 * Y.ustUste / Y.n).toFixed(0)}% · yerleşim kararı refleks dışı ${pc(R.flatMap(r => Array(r.yerKarar.n).fill(0).map((_, j) => j < r.yerKarar.disi)), x => x)}`); } }
